SAPCMControlZone: Fixed su-calls, fixed grep patterns, added TOODs for special output of mzshell commands

diff --git a/ra/SAPCMControlZone b/ra/SAPCMControlZone
--- a/ra/SAPCMControlZone
+++ b/ra/SAPCMControlZone
@@ -53,7 +53,12 @@ OCF_SUCCESS="${OCF_SUCCESS:-0}"
 function mz_component_startup()
 {
     local user="$1" component="$2" rc=0
-    su - "$user" "$mz_shell_central" startup "$component" | grep -qi "starting $component...done."; rc="$?"
+    # TODO PRIO1: set env for variables JAVA_HOME and MZ_HOME
+    #             su - v3zadm -c "JAVA_HOME=/opt/cm/V3Z/sapmachine17 MZ_HOME=/opt/cm/V3Z/CMP01/CM /opt/cm/V3Z/CMP01/CM/bin/mzsh startup platform"
+    # TODO PRIO1: out for already started component is "platform is already running"
+    # TODO PRIO1: Output like "FAILED\nStartable platform exited unexpectedly"
+    # TODO PRIO1: Tested, but not committed API: RC==0 OK
+    su - "$user" -c "$mz_shell_central startup $component" | grep -q "Starting $component...done."; rc="$?"
     return "$rc"
 }
 #export -f mz_component_startup
@@ -61,7 +66,14 @@ function mz_component_startup()
 function mz_component_shutdown()
 {
     local user="$1" component="$2" rc=0
-    su - "$user" "$mz_shell_central" shutdown "$component" | grep -q "Shutting down $component...done."; rc="$?"
+    # TODO PRIO1: set env for variables JAVA_HOME and MZ_HOME
+    # TODO PRIO1: How to treat output like "Shutting down platform...\nShutdown failed. Trying kill instead.\ndone."
+    # TODO PRIO1: How to treat output with unequal 3 dots (Shutting down platform....done.)
+    # TODO PRIO1: Output fror already stopped component is "<component> is not running"
+    # TODO PRIO1: Output like "Starting ui...FAILED"
+    # TODO PRIO1: Output like "platfoam: no such server process"
+    # TODO PRIO1: Tested, but not committed API: RC==0 OK
+    su - "$user" -c "$mz_shell_central shutdown $component" | grep -q "Shutting down $component....done."; rc="$?"
     return "$rc"
 }
 #export -f mz_component_shutdown
@@ -70,7 +82,11 @@ function mz_component_shutdown()
 function mz_component_status()
 {
     local user="$1" component="$2" rc=0
-    su - "$user" "$mz_shell_local" status | grep -q "$component is running"; rc="$?"
+    # TODO PRIO1: How to treat output like "platform is running without ..." 
+    # TODO PRIO1: set env for variables JAVA_HOME and MZ_HOME
+    # TODO PRIO1: Tested, but not committed API: status <component> does also work
+    # TODO PRIO1: Tested, but not committed API: RC==0 UP, RC==1 DEGRADED; RC==2 DOWN (one or multiple), OTHER: ERROR (FATAL)
+    su - "$user" -c "$mz_shell_local status $component" | grep -q "$component is running"; rc="$?"
     return "$rc"
 }
 export -f mz_component_status
@@ -159,11 +175,13 @@ function mz_call()
                 ;;
         kill )
                 # needs to switch-user to <mzadmin>
+                # TODO PRIO1: How to treat that kill outputs "platform not running" (not killing)
+                #             This occures e.g. if the component is already down.
                 if su - "$user" "$mz_shell_central" kill "$component" | grep -q "killing $component\.*done."; then
                     ocf_log info "mz_call: killing $component successful"
                     rc="$OCF_SUCCESS"
                 else
-		    # TODO maybe killing processes directly as last try? 
+                    # TODO PRIO2: maybe killing processes (with OS command kill) directly as last try? 
                     ocf_log info "mz_call: killing $component NOT successful"
                     rc="$OCF_ERR_GENERIC"
                 fi
